apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coolbeans.fullname.proxy" . }}
  labels:
    {{- include "coolbeans.labels.proxy" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "coolbeans.selectorLabels.proxy" . | nindent 6 }}
  {{- if not .Values.proxy.autoscaling.enabled }}
  replicas: {{ .Values.proxy.replicaCount }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "coolbeans.labels.proxy" . | nindent 4 }}
    spec:
      {{- if or .Values.topologySpreadConstraints.zone .Values.topologySpreadConstraints.hostname }}
      topologySpreadConstraints:
      {{- if .Values.topologySpreadConstraints.zone }}
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            {{- include "coolbeans.selectorLabels.proxy" . | nindent 12 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints.hostname }}
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            {{- include "coolbeans.selectorLabels.proxy" . | nindent 12 }}
      {{- end }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "coolbeans.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "/root/coolbeans",
          "beanstalkd",
          "--listen-port", "$(BEANSTALKD_PORT)",
          "--upstream-addrs", "$(PEERS_ADDRS)",
          "--max-job-size", "$(MAX_JOB_SIZE_BYTES)"]
        ports:
          - containerPort: 11300
            name: beanstalkd-tcp
        resources:
          {{- toYaml .Values.proxy.resources | nindent 12 }}
        env:
        - name: BEANSTALKD_PORT
          valueFrom:
            configMapKeyRef:
              name: coolbeans-config
              key: BEANSTALKD_PORT
        - name: PEERS_ADDRS
          valueFrom:
            configMapKeyRef:
              name: coolbeans-config
              key: PEERS_ADDRS
        - name:  MAX_JOB_SIZE_BYTES
          valueFrom:
            configMapKeyRef:
              name: coolbeans-config
              key: MAX_JOB_SIZE_BYTES
      restartPolicy: Always