
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coolbeans.fullname" . }}
  labels:
    {{- include "coolbeans.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: grpc-server
      port: 11000
      targetPort: 11000
    - name: raft-tcp
      port: 21000
      targetPort: 21000
  selector:
    {{- include "coolbeans.selectorLabels" . | nindent 4 }}