
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coolbeans.fullname" . }}-node
  labels:
    {{- include "coolbeans.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: grpc-server
      port: {{ .Values.clusterNode.config.coolbeans_rpc_port | default "11000" }}
      targetPort: grpc-server
    - name: raft-tcp
      port: {{ .Values.clusterNode.config.coolbeans_raft_port | default "21000" }}
      targetPort: raft-tcp
    - name: metrics
      port: {{ .Values.clusterNode.config.prometheus_port | default "2020" }}
      targetPort: metrics
  selector:
    {{- include "coolbeans.selectorLabels" . | nindent 4 }}
